version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building React application...
      - npm run build

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  base-directory: dist
  files:
    - '**/*'